from langgraph.graph import END, StateGraph
from langchain_core.messages import HumanMessage, AIMessage
from typing import Tuple, Optional

import streamlit as st
import time
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
import logging
logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO)

from src.states import AgentInput, AgentOutput, OverallState
from src.nodes import (
    question_rewriter,
    question_classifier,
    get_news,
    combine_news,
    on_topic_response,
    off_topic_response,
)
from src.edges import on_topic_router, news_router

workflow = StateGraph(OverallState, input=AgentInput, output=AgentOutput)

workflow.add_node(
    "question_rewriter",
    question_rewriter
)
workflow.add_node(
    "question_classifier",
    question_classifier
)
workflow.add_node('get_news', get_news)
workflow.add_node("combine_news", combine_news)
workflow.add_node("on_topic_response", on_topic_response)
workflow.add_node("off_topic_response", off_topic_response)


workflow.add_edge("question_rewriter", "question_classifier")
workflow.add_edge("get_news", "combine_news")
workflow.add_edge("combine_news", "on_topic_response")

workflow.add_conditional_edges(
    "question_classifier",
    on_topic_router,
    {
        "yes": "get_news",
        "no": "off_topic_response",
    }
)


workflow.add_conditional_edges(
    "combine_news",
    news_router,
    {
        "get_more_news": "get_news",
        "on_topic_response": "on_topic_response",
    }
)

workflow.add_edge("on_topic_response", END)
workflow.add_edge("off_topic_response", END)
workflow.set_entry_point("question_rewriter")
graph = workflow.compile()

#input_data = {"question": HumanMessage(content="What are the top five news of the day in AI and the food industry?")}
#result = graph.invoke(input_data)
#print(result)

#-------------------------------
# Streamlit app
#-------------------------------

# ---------- CONFIG ----------
st.set_page_config(page_title="NewsGeny", layout="wide")
st.title("🗞️ NewsGeny")

# ---------- INITIAL STATE ----------
if "last_response" not in st.session_state:
    st.session_state["last_response"] = ""
if "question_input" not in st.session_state:
    st.session_state["question_input"] = ""

# ---------- FUNCTION ----------
def extract_question_label(question: str) -> str:
    """
    Limpia la pregunta del usuario para usarla como etiqueta legible.
    Ejemplo:
      'What are the latest AI news in food industry?' → 'AI news in food industry'
    """
    if not question:
        return ""

    q = question.strip()

    # Pasa todo a minúsculas para procesar
    q_clean = q.lower()

    # Elimina palabras comunes al inicio
    q_clean = re.sub(r'^(what( are| is)?( the)?|show me|give me|tell me( about)?|latest|news( on| about)?)\s+', '', q_clean)

    # Quita signos de puntuación finales
    q_clean = q_clean.rstrip('?.!,;:')

    # Capitaliza solo la primera letra para mostrar bonito
    q_label = q_clean[0].upper() + q_clean[1:] if q_clean else ""

    return q_label


def generate_response():
    question = st.session_state["question_input"].strip()

    if not question:
        st.warning("Please enter a question.")
        return

    # 🔹 Limpia variables anteriores antes de procesar
    st.session_state["last_response"] = ""
    question_label = extract_question_label(question)

    try:
        with st.spinner("🔍 Fetching latest news..."):
            # Ejecuta el grafo
            input_data = {"question": HumanMessage(content=question)}
            result = graph.invoke(input_data)

        ai_response = None

        # 🧩 1️⃣ Caso principal: el grafo devuelve un dict con mensajes
        if isinstance(result, dict) and "messages" in result:
            for msg in reversed(result["messages"]):
                if isinstance(msg, AIMessage) and msg.content.strip():
                    ai_response = msg.content.strip()
                    break

        # 🧩 2️⃣ Caso alternativo: el grafo devuelve un solo AIMessage
        elif isinstance(result, AIMessage) and result.content.strip():
            ai_response = result.content.strip()

        # 🧩 3️⃣ Fallback: busca texto plano por si acaso
        elif isinstance(result, dict):
            for val in result.values():
                if isinstance(val, str) and val.strip():
                    ai_response = val.strip()
                    break

        # 🧩 4️⃣ Si no hay respuesta del modelo (None o vacío)
        if not ai_response:
            st.session_state["last_response"] = (
                "⚠️ No response generated by the model — try rephrasing your question."
            )
            return

        # 🧩 5️⃣ Si la respuesta es de tipo “off-topic” (según tu nodo)
        if "unrelated to news" in ai_response.lower():
            st.session_state["last_response"] = (
                f"🧭 **Your question seems off-topic:** {ai_response}"
            )
            return

        # 🧩 6️⃣ Si hay respuesta válida → formatear título Markdown
        lines = ai_response.splitlines()
        if lines:
            # reemplaza la primera línea si contiene el título estándar
            if "Top 10 News Articles" in lines[0]:
                lines[0] = f"### 📰 Top 10 News Articles on {question_label}"
            else:
                # si no hay título, lo agrega al inicio
                lines.insert(0, f"### 📰 Top 10 News Articles on {question_label}")
                lines.insert(1, "")
        else:
            lines = [f"### 📰 Top 10 News Articles on {question_label}", ""]

        ai_response = "\n".join(lines)
        st.session_state["last_response"] = ai_response

    except Exception as e:
        st.error(f"⚠️ Error generating response: {e}")
    finally:
        # 🔹 Limpia el input siempre (aunque haya error)
        st.session_state["question_input"] = ""


# ---------- UI ----------
# 🔹 Input fijo arriba
st.markdown("### Ask for the latest news")
st.text_input(
    "What news are you looking for?",
    key="question_input",
    on_change=generate_response,
    placeholder="e.g., latest AI developments in healthcare",
)
st.button("Submit", on_click=generate_response)

st.markdown("---")

# 🔹 Resultado abajo
if st.session_state["last_response"]:
    response_text = st.session_state["last_response"]  # keep as string
    # Render once
    st.markdown(response_text, unsafe_allow_html=True, width="content")

